### PR TITLE
Bet

### PR DESCRIPTION
**Pull request by SpencerSurface**
Add page to view information about individual bets

### CODE REVIEW

**Review by noah-10 — COMMENTED** [review]
For some of the bets I would get an error: Cannot read properties of undefined (reading 'username')
    at C:\Users\noahf\project-2\controllers\homeRoutes.js:98:83

**Comment by SpencerSurface** [comment]
> For some of the bets I would get an error: Cannot read properties of undefined (reading 'username') at C:\Users\noahf\project-2\controllers\homeRoutes.js:98:83

Okay, I'll look into that

**Comment by SpencerSurface** [comment]
I fixed two different issues.
1) Some of the seed data could have bets created by users who didn't have stakes in the bet, so I updated the seeding code to include each bet's created_by user in one of its stakes.
2) For bets that don't exist, the page shows an error, so I created a 404 Not Found page to redirect to.
Let me know if you see anything else that needs fixed.

**Review by noah-10 — APPROVED** [review]
Looks good!

**Pull request merged**
